#   10 September 2025

In [3]:
import numpy as np
import matplotlib.pyplot as plt

We recall Ohm's Law as well as Kirchhoff's loop and junction rules:

$$V=\sum_{i}{I_iR_i}$$

where $i$ are all of the circuit elements in one loop. <br>
A loop is defined as beginning with a voltage source and considering all elements connected to it in series, which may end back to the voltage source or to ground, $V=0$. We also define an arbitrary positive direction (usually CCW) to which the signs of the terms per element will be derived from. An individual loop is described by one Ohm's Law equation counting all of its constituents, where we propose that a specific magnitude of current is passing through an element. If a junction is met, we assume that any incoming current to that junction must be equal to the outgoing current in magnitude; the equation derived from this is often expressed in sums of the incoming/outgoing currents.

![Test Circuit 1.](./sample_kirch.png)

In the above test circuit, we then see that there are three loops to consider:

$$-V_1 = -I_1R_1 -I_2R_2$$
$$-V_2 = -I_2R_2 -I_4R_4$$
$$+V_2 = -I_1R_1 -I_3R_3$$

Note that we are trying to determine/calculate the current $I_i$ that goes through each component. As there are 4 components (unknowns), we then also need 4 equations. Thus we can call upon the junction rule in specific junctions, such as before $R1$

##   A resistor network.

We consider the diagram below where $N$ is a variable **even** amount of junctions on its top and bottom edge. Based from the diagram as well, $N$ also counts the number of three-resistor loops in the network. In this, we can consider 4 unique resistance values: $R_1$, which are all of the resistors in the top edge; $R_2$, which are all of the bottom edge; $R_3$, which are all the odd-to-even (such as the $V_1 \to V_2$ resistor); and $R_4$, which are the even-to-odd (such as the $V_2 \to V_3$ resistor).

![Resistor Network.](./resistor_network.png)

Arbitrarily, let the diagram above has $V_+=5 \text{ volts}$.

Recall that the effective resistance can be computed whether the network is in series or parallel.

$$R_{\text{eff, ser}} = \sum_i R_i$$
$$R_{\text{eff, par}} = \frac{1}{\sum_i {\frac{1}{R_i}}}$$

where $i$ is an element of the circuit, and from Ohm's Law,

$$ R_{\text{eff}} = \frac{V}{I_\text{eff}}$$

From our lab instructor's tip, we take the third equation, where the effective current $I_{\text{eff}}$ going through the circuit is solvable. 

Note that for an even $N$, we have the following properties:
- number of resistors per type $N_i$; $i \in {1, 2, 3, 4}$:
    - $N_1 = N_2 = N_3 = \frac{1}{2}N$
    - $N_4 = \frac{1}{2}N+1$
- number of unknown currents, which is based on the total number of resistors.
    - $N_{\text{total}} = 2N+1$
    - This is also the amount of needed equations, and thus the amount of rows and columns of the matrix $\vec{A}$ and the size of vector $\vec{I}$.
- size of matrix $\vec{A}$ is $N_{\text{total}} \text{ by } N_{\text{total}}$

Note that loops can be constructed from the voltage source $V_0 = V_{+}$ to the ground line $V_{N+1} = 0$. We can take the following paths:
1. Going through the top edge only.
2. Going through the bottom edge only.

This already gives us $2$ equations.

In [18]:
def circuit_mat(N=2, R1=1, R2=1, R3=1, R4=1):
    dim=2*N+1
    A = np.zeros((dim, dim))
    I = np.zeros((dim, 1))

    #   Populating each row with Kirchhoff's rules.
    for col in range(dim):
        for row in range(dim):
            pass
    return A, I

In [16]:
V_in = 5
res = circuit_mat()
print(f'{res[0]} \n {res[1]}')

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
